---
- name: Update the system cache
  become: yes
  when: cache_update
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the system packages
  become: yes
  when: system_upgrade
  ansible.builtin.apt:
    upgrade: "full"

- name: Install packages
  become: yes
  when: packages is defined
  ansible.builtin.apt:
    pkg: "{{ packages }}"
