---
- name: Add gpg key for indi source
  become: yes
  ansible.builtin.apt_key:
    url: "https://www.astroberry.io/repo/key"
    state: present

- name: Add astroberry as a source in apt
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://www.astroberry.io/repo/ {{ debian_distro }} main
    state: present
