---
- name: Downloads oh my posh installer
  register: oh_my_posh_installer
  when: install_prompt is defined and install_prompt
  ansible.builtin.uri:
    url: https://ohmyposh.dev/install.sh
    return_content: yes

- name: Install oh-my-posh
  when: install_prompt is defined and install_prompt
  ansible.builtin.shell:
    cmd: sh
    stdin: "{{ oh_my_posh_installer.content }}"

- name: Upgrade oh-my-posh
  when: upgrade_prompt
  ansible.builtin.shell:
    cmd: oh-my-posh upgrade
